"""create_initial_tables

Revision ID: 7cdcee36b7a6
Revises: 
Create Date: 2025-05-15 21:38:57.634780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cdcee36b7a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('game_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_player_name'), 'players', ['player_name'], unique=True)
    op.create_table('game_odds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('home_team_odds', sa.Float(), nullable=True),
    sa.Column('away_team_odds', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('over_under', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_prop_odds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('over_odds', sa.Integer(), nullable=False),
    sa.Column('under_odds', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('rebounds', sa.Float(), nullable=True),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('steals', sa.Float(), nullable=True),
    sa.Column('blocks', sa.Float(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.Column('minutes_played', sa.Float(), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('player_prop_odds')
    op.drop_table('game_odds')
    op.drop_index(op.f('ix_players_player_name'), table_name='players')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
