from pydantic import BaseModel, ConfigDict
from datetime import date

class PlayerStatBase(BaseModel):
    player_name: str
    team_name: str
    points: float | None = None
    rebounds: float | None = None
    assists: float | None = None
    steals: float | None = None
    blocks: float | None = None
    turnovers: float | None = None
    minutes_played: float | None = None
    game_date: date | None = None

class PlayerStatCreate(PlayerStatBase):
    pass

class PlayerStat(PlayerStatBase):
    player_id: int # Assuming player_id is generated by the DB or known

    model_config = ConfigDict(from_attributes=True) 